# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15vXhtDNinpEH0kBueJlzfps_Ypt-1kqj
"""

#3*3 matrix oluşturma
a = [[1, 2, 3], [4,5, 6], [7, 8, 9]]
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')
    print()

#asal sayıların listesi
number = []
for sayi in range(2,24):
  for i in range(2,sayi):
       if (sayi % i) == 0:
           break
  else:
    number.append(sayi)
     
print(number)

#3*3 matrixs asal sayı
number = []
for sayi in range(2,24):
  for a in range(2,sayi):
       if (sayi % a) == 0:
           break
  else:
    number.append(sayi)
for i in range(len(number)):
  for j in range(len(number)):
    print(number[i][j],end = " ")
  print()

